### ISSUE TITLE
在win10 21h1上测试失败,

### ISSUE THREAD

**Issue by test-for-play** [crisprss/PetitPotam#1]
![image](https://user-images.githubusercontent.com/80519861/159235336-8f3c7fe1-ef3d-4b20-a912-e798d722ed87.png)

**Comment by crisprss** [comment]
最近我观察到微软好像修复UNC Spoofing了，至少修复了PetitPotam的Spoofing，你的版本可能被修复了(x

**Comment by test-for-play** [comment]
应该是的 在最新的server2019上也失败 在我没更新sever2019之前是成功的 更新重启后就不行了

**Comment by crisprss** [comment]
是的，我之前遇到了，微软悄悄修复了-.-
